# Generated by Django 5.1.6 on 2025-02-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='emailuser',
            name='last_name',
        ),
    ]
