"""Update user

Revision ID: 11ac559f37f9
Revises: 6b23a2874bc4
Create Date: 2025-03-12 09:49:12.459349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '11ac559f37f9'
down_revision: Union[str, None] = '6b23a2874bc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_user', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('email_user', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('email_user', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('email_user', sa.Column('is_staff', sa.Boolean(), nullable=False))
    op.add_column('email_user', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_user', 'created_at')
    op.drop_column('email_user', 'is_staff')
    op.drop_column('email_user', 'is_active')
    op.drop_column('email_user', 'password_hash')
    op.drop_column('email_user', 'username')
    # ### end Alembic commands ###
