services:
  db:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  web:
    ports:
      - '8000:8000'
    environment:
      - DJANGO_ENV=production
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py create_superuser &&
             gunicorn django_blog.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    expose:
      - '8000'

  nginx:
    image: nginx:latest
    ports:
      - '8001:80'
      - '8443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
      - ./static:/static
      - ./media:/media
    depends_on:
      - web
