services:
  db:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  web:
    ports:
      - '8000:8000'
    environment:
      - DJANGO_ENV=development
