version: '3.8'

services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - ./media:/app/media
      - ../shared:/shared
    ports:
      - '8000:8000'
    environment:
      - DJANGO_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
    command: >
      sh -c "python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py create_superuser &&
            python manage.py seed &&
            python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
