version: '3.8'

services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_DB:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_DB:-postgres}
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - .:/app
      - ./media:/app/media
      - ../shared:/shared
    depends_on:
      - db
    command: >
      sh -c "python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py create_superuser &&
            python manage.py seed &&
            python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
