version: '3.8'

services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_DB:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_DB:-postgres}
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./media:/app/media
      - ../shared:/shared
    ports:
      - '5000:5000'
    depends_on:
      - db
    command: >
      sh -c "flask db upgrade &&
             flask create-superuser &&
             flask seed run &&
             flask run --host=0.0.0.0 --port=5000"

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./media:/app/media
      - ../shared:/shared
    environment:
      - TESTING=True
    depends_on:
      - db
    command: pytest
    profiles:
      - test

volumes:
  postgres_data:
