services:
  db:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'

  web:
    ports:
      - '5000:5000'
    environment:
      - FLASK_ENV=production
    volumes:
      - ./media:/app/media
      - ../shared/static:/app/static
    command: >
      sh -c "flask db upgrade &&
             flask create-superuser &&
             gunicorn --bind 0.0.0.0:5000 'flask_blog:create_app()'"

  nginx:
    image: nginx:latest
    ports:
      - '5001:80'
      - '5443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
      - ./media:/media
      - ../shared/static:/static
    depends_on:
      - web
