services:
  db:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'

  web:
    ports:
      - '5000:5000'
    environment:
      - FLASK_ENV=development
      - FLASK_APP=flask_blog:create_app
