version: '3.8'

services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - ./media:/app/media
      - ../shared:/shared
    ports:
      - '5000:5000'
    environment:
      - FLASK_ENV=development
      - FLASK_APP=flask_blog
      - DATABASE_URI=postgresql://postgres:postgres@db:5432/postgres
      - SECRET_KEY=dev_secret_key_replace_in_production
      - USE_LOCAL_STORAGE=True
    depends_on:
      - db
    command: >
      sh -c "flask db upgrade &&
             flask create-superuser &&
             flask run --host=0.0.0.0 --port=5000"

volumes:
  postgres_data:
