services:
  db:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5434:5432'

  web:
    ports:
      - '7000:7000'
    environment:
      - FASTAPI_ENV=prod
    volumes:
      - ./media:/app/media
      - ../shared/static:/app/static
    command: >
      sh -c "alembic upgrade head &&
             python -m fastapi_blog.utils.create_superuser &&
             uvicorn fastapi_blog.main:app --proxy-headers --host 0.0.0.0 --port 7000 --reload"

  nginx:
    image: nginx:latest
    ports:
      - '7001:80'
      - '7443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
      - ./media:/media
      - ../shared/static:/static
    depends_on:
      - web
