services:
  db:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5434:5432'

  web:
    ports:
      - '7000:7000'
    environment:
      - FASTAPI_ENV=dev
