@startuml erd

hide circle
skinparam Linetype ortho

entity User {
    * id: int
    --
    * username: string
    * email: string
    * password_hash: string
    * created_at: datetime
}

entity BlogPost {
    * id: int
    --
    * title: string
    * text: string
    image: string
    * created_at: datetime
    * user_id: uuid <<FK>>
}

entity Tag {
    * id: int
    --
    * name: string
}

entity BlogPostTag {
    * blog_id: int <<FK>>
    * tag_id: int <<FK>>
}

User ||--o{ BlogPost
BlogPost ||--o{ BlogPostTag
Tag ||--o{ BlogPostTag

@enduml